- name: Download and extract tar file
  block:
    - name: Download Tar
      ansible.builtin.get_url:
        url: "{{ app_archive_url }}"
        dest: "{{ app_tmp_file }}"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0750"

    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ app_tmp_path }}"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        state: directory
        mode: "0750"

    - name: Extract archive to temporary path
      ansible.builtin.unarchive:
        src: "{{ app_tmp_file }}"
        dest: "{{ app_tmp_path }}"
        remote_src: true

    - name: Delete tar file
      ansible.builtin.file:
        path: "{{ app_tmp_file }}"
        state: absent

- name: Install Application
  block:
    - name: Copy temporary path to homepath
      ansible.builtin.copy:
        src: "{{ app_tmp_path }}/"
        dest: "{{ app_home }}"
        owner: "{{ app_name }}"
        group: "{{ app_name }}"
        remote_src: true
        mode: "0750"

    - name: Delete temporary path
      ansible.builtin.file:
        path: "{{ app_tmp_path }}"
        state: absent

    - name: Create SymLink for the App
      ansible.builtin.file:
        src: "{{ binary_source_path }}"
        dest: "{{ binary_dest_path }}"
        owner: "{{ app_name }}"
        group: "{{ app_name }}"
        state: link
        mode: "0555"
