- name: Update Packages And Add Required Packages
  block:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Prerequisites
      ansible.builtin.apt:
        name: "{{ apt_packages | from_yaml }}"
        state: present

- name: Create Service Account
  block:
    - name: Create Group
      ansible.builtin.group:
        name: "{{ app_name }}"
        state: present

    - name: Create user
      ansible.builtin.user:
        name: "{{ app_name }}"
        comment: "Service account for running {{ app_name }}"
        shell: /usr/sbin/nologin
        home: "{{ app_home }}"
        create_home: true
        system: true
